### PR TITLE
Add dark theme that applies on client settings

### LINKED ISSUE #24: Add dark theme
In my fork I've added a dark theme based on user device settings. I'll clean it up a bit and send a pull request.

### PR DESCRIPTION
**Pull request by Fleker**
Fixes #24

Here's a screenshot of how it looks. It might be worthwhile to update the buttons in this theme if you think so.

image

### CODE REVIEW

**Comment by RebornSerenity** [comment]
Please darken the grey/white bar, I have bad eyes and I have to edit the CSS when I turn on dark mode, I also have to edit the power colors, and that white, is way too much, perhaps something more along this Hex color instead: #53585c

The buttons are fine, they don't hurt as badly

**Comment by Fleker** [comment]
Okay I've modified the background bar. I've attached a new screenshot.

I see that all of the power colors are listed in the `COLORS` map in `utils.js`. Moving these to class names and doing it all in CSS might be a better approach. I could do that work here, or perhaps save for a follow-up PR?

image

**Comment by RebornSerenity** [comment]
That's wonderful, much easier on the eyes, looks great

**Comment by RebornSerenity** [comment]
no, that looks wonderful! THank you for working on it.

**Comment by Fleker** [comment]
Great. Anything that I should do before you merge?

**Comment by cecilbowen** [comment]
Looks good.  I merged it.  I did [change ](https://github.com/cecilbowen/pokemon-sandwich-simulator/commit/30b44e24f0390ad2f9d59625ffe764e4aecc00f3)a few things to match the dark theme, like the "Total Stats" header text and the Effect Filter bubble buttons' text.

**Pull request merged**
